# Generated by Django 4.0.2 on 2022-02-24 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobs.models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uid', models.CharField(default=jobs.models.generate_uid, max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', martor.models.MartorField()),
                ('name_of_facility', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('locum', 'Locum'), ('permanent', 'Permanent')], max_length=9)),
                ('name_of_town_or_city', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('northern', 'Northern'), ('ashanti', 'Ashanti'), ('western', 'Western'), ('volta', 'Volta'), ('eastern', 'Eastern'), ('upper west', 'Upper West'), ('upper east', 'Upper East'), ('greater accra', 'Greater Accra'), ('savannah', 'Savannah'), ('north east', 'North East'), ('bono east', 'Bono East'), ('oti', 'Oti'), ('ahafo', 'Ahafo'), ('western north', 'Western North')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', martor.models.MartorField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
