# Generated by Django 4.0.2 on 2022-02-23 22:03

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_comment_user_job_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='uid',
            field=models.CharField(default=jobs.models.generate_uid, max_length=12),
        ),
    ]
